%This code was used to extract the CMIP6 climate dataset
clear all
close all
myAttributes = {'tasmin', ...
    'tasmax',...
    'sfcWind',  ...
    'rsds', ...
    'pr', ...
    'hurs', ...
    };

for k=1:length(myAttributes);
%for k=1:1;
for i=2021:2022
fullURL=['https://ds.nccs.nasa.gov/thredds/ncss/AMES/NEX/GDDP-CMIP6/CanESM5/ssp585/r1i1p1f1/',myAttributes{k}...
    '/'...
    myAttributes{k} ...
    '_day_CanESM5_ssp585_r1i1p1f1_gn_' ...
    num2str(i), ...
    '.nc?var=' ...
    myAttributes{k} ...
    '&north=40.2&west=-88.2&east=-88&south=40' ...
    '&disableProjSubset=on&horizStride=1&time_start=', ...
    num2str(i), ...
    '-01-01T12%3A00%3A00Z&time_end=', ...
    num2str(i), ...
    '-12-31T12%3A00%3A00Z&timeStride=1'];

filename=[myAttributes{k}, '_day_CanESM5_ssp585_r1i1p1f1_gn_',num2str(i),'.nc'];

[f,status]=urlwrite(fullURL,filename);
end 



end 